# Generated by Django 3.0.4 on 2020-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=120)),
                ('confirmed_cases', models.IntegerField()),
                ('cases_per_million', models.CharField(max_length=120)),
                ('total_recovered', models.IntegerField()),
            ],
        ),
    ]
