# Generated by Django 3.0.4 on 2020-03-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
