# Generated by Django 3.0.4 on 2020-03-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_country_total_deaths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cases_per_million',
            field=models.CharField(default='--', max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.IntegerField(default=0),
        ),
    ]
