# Generated by Django 3.0.4 on 2020-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20200331_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
