# Generated by Django 3.0.4 on 2020-04-05 12:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_country_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coustomer_name', models.CharField(help_text='Enter your name', max_length=120)),
                ('coustomer_email', models.EmailField(help_text='Enter your email', max_length=254)),
                ('coustomer_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
