# Generated by Django 3.0.4 on 2020-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='confirmed_cases',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
