# Generated by Django 3.0.4 on 2020-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_auto_20200405_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coustomer_name',
            field=models.CharField(blank=True, help_text='Enter your name', max_length=120, null=True),
        ),
    ]
