# Generated by Django 3.0.4 on 2020-04-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_auto_20200405_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
