# Generated by Django 3.0.4 on 2020-04-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image_link',
        ),
    ]
