# Generated by Django 3.0.4 on 2020-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0009_remove_country_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='url',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='confirmed_cases',
            field=models.CharField(default='--', max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='--', max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.CharField(default='--', max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.CharField(default='--', max_length=120),
        ),
    ]
