# Generated by Django 3.0.4 on 2020-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_auto_20200413_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='---', max_length=3),
        ),
    ]
